// The dashboard schema is the source of truth for the control surface.
// As new env knobs are introduced in the runtimes, add them here so the UI,
// command preview, and saved presets stay aligned with the code.

export const TARGET_PRESETS = {
  all: {
    label: "All Knobs",
    launcher: "python train_gpt.py",
  },
  torch: {
    label: "PyTorch",
    launcher: "python train_gpt.py",
  },
  mlx: {
    label: "MLX",
    launcher: "python3 train_gpt_mlx.py",
  },
};

function field(definition) {
  return definition;
}

export const SETTINGS = [
  {
    title: "Run Identity",
    description: "Names, paths, and artifacts that tell the runtime what data to load and how to tag the run.",
    fields: [
      field({ env: "RUN_ID", label: "Run ID", type: "text", value: "weekend-run", targets: ["torch", "mlx"], help: "Human-readable tag for logs and exported artifacts." }),
      field({ env: "MANIFEST_PATH", label: "Manifest Path", type: "text", value: "", targets: ["torch"], help: "Optional JSON manifest path. Blank writes beside the log by default." }),
      field({ env: "STEP_TRACE_PATH", label: "Step Trace Path", type: "text", value: "", targets: ["torch"], help: "Optional JSONL trace path. Blank writes beside the log by default." }),
      field({ env: "DASHBOARD_PROFILE_NAME", label: "Dashboard Profile", type: "text", value: "", targets: ["torch"], help: "Optional profile label copied into the run manifest." }),
      field({ env: "TRAIN_SHARD_LIMIT", label: "Train Shard Limit", type: "number", value: 0, targets: ["torch"], help: "0 uses all resolved training shards; positive values keep only the first N after offset/order resolution." }),
      field({ env: "TRAIN_SHARD_OFFSET", label: "Train Shard Offset", type: "number", value: 0, targets: ["torch"], help: "Skips the first N resolved training shards before streaming." }),
      field({ env: "TRAIN_SHARD_ORDER_FILE", label: "Train Shard Order", type: "text", value: "", targets: ["torch"], help: "Optional newline-delimited shard order file." }),
      field({ env: "TRAIN_SHARD_LIST", label: "Train Shard List", type: "text", value: "", targets: ["torch"], help: "Optional comma-separated explicit shard list." }),
      field({ env: "SEED", label: "Seed", type: "number", value: 1337, targets: ["torch", "mlx"], help: "Random seed for init and data order." }),
      field({ env: "DATA_PATH", label: "Dataset Path", type: "text", value: "./data/datasets/fineweb10B_sp1024", targets: ["torch", "mlx"], help: "Directory containing train and validation shards." }),
      field({ env: "TOKENIZER_PATH", label: "Tokenizer Path", type: "text", value: "./data/tokenizers/fineweb_1024_bpe.model", targets: ["torch", "mlx"], help: "SentencePiece model used for byte accounting and token lookups." }),
      field({ env: "VOCAB_SIZE", label: "Vocab Size", type: "number", value: 1024, targets: ["torch", "mlx"], help: "Must match the tokenizer and embedding shape." }),
      field({ env: "OUT_DIR", label: "MLX Output Dir", type: "text", value: "logs", targets: ["mlx"], help: "Directory for MLX logs and outputs." }),
    ],
  },
  {
    title: "Training Schedule",
    description: "High-level timeline controls: how long training runs, when warmup happens, and how often the loop talks back.",
    fields: [
      field({ env: "ITERATIONS", label: "Iterations", type: "number", value: 400, targets: ["torch", "mlx"], help: "Target optimizer steps before stopping." }),
      field({ env: "MAX_WALLCLOCK_SECONDS", label: "Wallclock Seconds", type: "number", value: 630, targets: ["torch", "mlx"], help: "Hard wallclock cap; 0 disables the limit." }),
      field({ env: "WARMUP_STEPS", label: "Compile Warmup Steps", type: "number", value: 10, targets: ["torch", "mlx"], help: "Primes compile/allocation paths before measured training." }),
      field({ env: "LR_WARMUP_STEPS", label: "LR Warmup Steps", type: "number", value: 96, targets: ["torch", "mlx"], help: "Real optimizer warmup applied at the front of training." }),
      field({ env: "WARMDOWN_ITERS", label: "Warmdown Iters", type: "number", value: 1200, targets: ["torch", "mlx"], help: "Tail-phase LR decay window." }),
      field({ env: "VAL_LOSS_EVERY", label: "Val Loss Every", type: "number", value: 0, targets: ["torch", "mlx"], help: "Validation cadence; 0 means final validation only." }),
      field({ env: "TRAIN_LOG_EVERY", label: "Train Log Every", type: "number", value: 512, targets: ["torch", "mlx"], help: "Training log cadence after the first 10 steps." }),
      field({ env: "STEP_TRACE_EVERY", label: "Step Trace Every", type: "number", value: 1, targets: ["torch"], help: "JSONL step-trace cadence; 0 disables structured step tracing." }),
      field({ env: "COMPILE_DYNAMIC", label: "Compile Dynamic", type: "boolean", value: false, targets: ["torch"], help: "Allow torch.compile to handle changing shapes without specializing each exact sequence length." }),
      field({ env: "COMPILE_FULLGRAPH", label: "Compile Fullgraph", type: "boolean", value: true, targets: ["torch"], help: "Keep fullgraph mode for stable-shape runs; disable it for aggressive staged-shape curricula." }),
      field({ env: "DYNAMO_RECOMPILE_LIMIT", label: "Recompile Limit", type: "number", value: 8, targets: ["torch"], help: "Maximum Dynamo recompiles before hard failure. Raise this for multi-shape experiments." }),
    ],
  },
  {
    title: "Stage Scheduler",
    description: "Generic multi-stage schedule starts. Use either STAGE_FRACTIONS for progress-based starts or STAGE_STEP_STARTS for exact optimizer-step starts; each STAGE_* list provides one value per stage.",
    fields: [
      field({ env: "STAGE_FRACTIONS", label: "Stage Fractions", type: "text", value: "", targets: ["torch"], help: "Comma-separated stage starts in [0,1], beginning with 0.0. Example: 0.0,0.3,0.7." }),
      field({ env: "STAGE_STEP_STARTS", label: "Stage Step Starts", type: "text", value: "", targets: ["torch"], help: "Comma-separated exact optimizer-step starts beginning with 0. Use this instead of STAGE_FRACTIONS for shot-by-shot schedules." }),
      field({ env: "STAGE_TRAIN_BATCH_TOKENS", label: "Stage Batch Tokens", type: "text", value: "", targets: ["torch"], help: "Comma-separated batch token values, one per stage." }),
      field({ env: "STAGE_TRAIN_SEQ_LEN", label: "Stage Seq Len", type: "text", value: "", targets: ["torch"], help: "Comma-separated sequence lengths, one per stage." }),
      field({ env: "STAGE_EMA_ENABLED", label: "Stage EMA Enabled", type: "text", value: "", targets: ["torch"], help: "Comma-separated booleans like 0,0,1 or false,true,true." }),
      field({ env: "STAGE_EMA_DECAY", label: "Stage EMA Decay", type: "text", value: "", targets: ["torch"], help: "Comma-separated EMA decay values, one per stage." }),
      field({ env: "STAGE_TOK_LR_MUL", label: "Stage Tok LR", type: "text", value: "", targets: ["torch"], help: "Comma-separated token-role LR multipliers, one per stage." }),
      field({ env: "STAGE_HEAD_LR_MUL", label: "Stage Head LR", type: "text", value: "", targets: ["torch"], help: "Comma-separated head-role LR multipliers, one per stage." }),
      field({ env: "STAGE_MATRIX_LR_MUL", label: "Stage Matrix LR", type: "text", value: "", targets: ["torch"], help: "Comma-separated matrix-role LR multipliers, one per stage." }),
      field({ env: "STAGE_SCALAR_LR_MUL", label: "Stage Scalar LR", type: "text", value: "", targets: ["torch"], help: "Comma-separated scalar-role LR multipliers, one per stage." }),
      field({ env: "STAGE_MUON_MOMENTUM", label: "Stage Muon Mom", type: "text", value: "", targets: ["torch"], help: "Comma-separated Muon momentum targets, one per stage." }),
      field({ env: "STAGE_BIGRAM_SCALE", label: "Stage Bigram Scale", type: "text", value: "", targets: ["torch"], help: "Comma-separated BigramHash additive scales, one per stage." }),
    ],
  },
  {
    title: "Batching",
    description: "Controls the token budget seen per optimizer step and how that budget is split across microbatches.",
    fields: [
      field({ env: "TRAIN_BATCH_TOKENS", label: "Train Batch Tokens", type: "number", value: 524288, targets: ["torch", "mlx"], help: "Total training tokens consumed per optimizer step." }),
      field({ env: "BATCH_TOKENS_START", label: "Batch Tokens Start", type: "number", value: 0, targets: ["torch"], help: "0 disables batch curriculum; positive values use a smaller starting token budget before switching to TRAIN_BATCH_TOKENS." }),
      field({ env: "BATCH_SCHEDULE_FRACTION", label: "Batch Schedule Fraction", type: "number", value: 0.0, targets: ["torch"], help: "Fraction of the run after which batch tokens switch from start to final value." }),
      field({ env: "TRAIN_SEQ_LEN", label: "Train Seq Len", type: "number", value: 1024, targets: ["torch", "mlx"], help: "Context length used during training." }),
      field({ env: "SEQ_LEN_START", label: "Seq Len Start", type: "number", value: 0, targets: ["torch"], help: "0 disables sequence curriculum; positive values use a shorter starting context before switching to TRAIN_SEQ_LEN." }),
      field({ env: "SEQ_SCHEDULE_FRACTION", label: "Seq Schedule Fraction", type: "number", value: 0.0, targets: ["torch"], help: "Fraction of the run after which sequence length switches from start to final value." }),
      field({ env: "TRAIN_MAX_SEQ_LEN", label: "MLX Train Max Seq Len", type: "number", value: 1024, targets: ["mlx"], help: "Fallback used by MLX when TRAIN_SEQ_LEN is unset." }),
      field({ env: "VAL_BATCH_SIZE", label: "Val Batch Size", type: "number", value: 524288, targets: ["torch", "mlx"], help: "Validation token budget per pass." }),
      field({ env: "TARGET_GLOBAL_ACCUM", label: "Target Global Accum", type: "number", value: 16, targets: ["torch"], help: "PyTorch effective global accumulation target. Keep it shape-compatible with batch and seq length." }),
      field({ env: "GRAD_ACCUM_STEPS", label: "MLX Grad Accum Steps", type: "number", value: 8, targets: ["mlx"], help: "Explicit accumulation count on the MLX path." }),
      field({ env: "MLX_MAX_MICROBATCH_TOKENS", label: "MLX Max Microbatch Tokens", type: "number", value: 8192, targets: ["mlx"], help: "Caps per-subbatch tokens to keep unified-memory use sane." }),
      field({ env: "MLX_EAGER_EVAL", label: "MLX Eager Eval", type: "boolean", value: true, targets: ["mlx"], help: "Materialize each microbatch to keep memory bounded." }),
    ],
  },
  {
    title: "Evaluation",
    description: "Knobs that affect how the model is judged or which weights are used at eval time, separate from core training.",
    fields: [
      field({ env: "EVAL_STRIDE", label: "Eval Stride", type: "number", value: 0, targets: ["torch"], help: "0 uses chunked eval; positive values enable sliding eval." }),
      field({ env: "EVAL_POLICY", label: "Eval Policy", type: "text", value: "auto", targets: ["torch"], help: "auto chooses from EVAL_STRIDE; explicit options are chunked or sliding." }),
      field({ env: "EVAL_MAX_TOKENS", label: "Eval Max Tokens", type: "number", value: 0, targets: ["torch"], help: "0 uses the full validation set; positive values cap validation tokens for quick probes." }),
      field({ env: "EVAL_SUBSET_MODE", label: "Eval Subset Mode", type: "text", value: "full", targets: ["torch"], help: "full/head/tail selection when EVAL_MAX_TOKENS is active." }),
      field({ env: "EVAL_STRICT_FULL", label: "Eval Strict Full", type: "boolean", value: true, targets: ["torch"], help: "Rejects partial validation settings when strict/full mode is required." }),
      field({ env: "EMA_ENABLED", label: "EMA Enabled", type: "boolean", value: false, targets: ["torch"], help: "Uses EMA weights for eval and serialization." }),
      field({ env: "EMA_DECAY", label: "EMA Decay", type: "number", value: 0.997, targets: ["torch"], help: "Higher values smooth more but lag the live weights longer." }),
      field({ env: "LOGIT_CHUNK_TOKENS", label: "MLX Logit Chunk Tokens", type: "number", value: 0, targets: ["mlx"], help: "Splits large logit computations into smaller chunks." }),
    ],
  },
  {
    title: "Model Shape",
    description: "The structural dimensions of the model itself: depth, width, heads, and positional scaling.",
    fields: [
      field({ env: "NUM_LAYERS", label: "Num Layers", type: "number", value: 9, targets: ["torch", "mlx"], help: "Total transformer block count." }),
      field({ env: "MODEL_DIM", label: "Model Dim", type: "number", value: 512, targets: ["torch", "mlx"], help: "Residual channel width." }),
      field({ env: "NUM_HEADS", label: "Num Heads", type: "number", value: 8, targets: ["torch", "mlx"], help: "Attention query head count." }),
      field({ env: "NUM_KV_HEADS", label: "Num KV Heads", type: "number", value: 4, targets: ["torch", "mlx"], help: "Key/value head count for GQA-style sharing." }),
      field({ env: "MLP_MULT", label: "MLP Mult", type: "number", value: 2, targets: ["torch", "mlx"], help: "Expansion ratio for the feedforward hidden width." }),
      field({ env: "TIE_EMBEDDINGS", label: "Tie Embeddings", type: "boolean", value: true, targets: ["torch", "mlx"], help: "Shares input embedding weights with the output projection." }),
      field({ env: "TIED_EMBED_INIT_STD", label: "Tied Embed Init Std", type: "number", value: 0.005, targets: ["torch", "mlx"], help: "Init std used when embeddings are tied." }),
      field({ env: "BIGRAM_VOCAB_SIZE", label: "Bigram Vocab Size", type: "number", value: 0, targets: ["torch"], help: "0 disables BigramHash; positive values set the hash-table bucket count." }),
      field({ env: "BIGRAM_DIM", label: "Bigram Dim", type: "number", value: 128, targets: ["torch"], help: "Embedding width of the BigramHash table before optional projection to model_dim." }),
      field({ env: "BIGRAM_SCALE_INIT", label: "Bigram Scale Init", type: "number", value: 0.05, targets: ["torch"], help: "Initial additive scale applied to the BigramHash feature path." }),
      field({ env: "USE_SMEARGATE", label: "Use SmearGate", type: "boolean", value: false, targets: ["torch"], help: "Blends each token embedding with the previous token embedding before the transformer stack." }),
      field({ env: "SMEAR_GATE_INIT", label: "Smear Gate Init", type: "number", value: 3.0, targets: ["torch"], help: "Initial SmearGate bias before sigmoid; higher values start closer to pass-through." }),
      field({ env: "ROPE_BASE", label: "RoPE Base", type: "number", value: 10000, targets: ["torch", "mlx"], help: "Base frequency scale for rotary position embeddings." }),
      field({ env: "ROPE_DIMS", label: "RoPE Dims", type: "number", value: 0, targets: ["torch"], help: "0 rotates the full head; smaller even values rotate only a prefix of each head." }),
      field({ env: "XSA_LAST_N", label: "XSA Last N", type: "number", value: 0, targets: ["torch"], help: "Turns on XSA only for the last N transformer blocks." }),
      field({ env: "XSA_LAYER_MASK", label: "XSA Layer Mask", type: "text", value: "", targets: ["torch"], help: "Optional explicit XSA mask. Supports comma 0/1 lists, all, none, tail:N, or head:N." }),
      field({ env: "LOGIT_SOFTCAP", label: "Logit Softcap", type: "number", value: 30.0, targets: ["torch", "mlx"], help: "Tanh-based cap applied to logits before cross-entropy." }),
      field({ env: "QK_GAIN_INIT", label: "QK Gain Init", type: "number", value: 1.5, targets: ["torch", "mlx"], help: "Initial scaling applied inside attention q/k paths." }),
    ],
  },
  {
    title: "Control Tensor Init",
    description: "Role-wise initialization for the small control tensors that shape residual mixing, attention scaling, and skip behavior.",
    fields: [
      field({ env: "ATTN_SCALE_INIT", label: "Attn Scale Init", type: "number", value: 1.0, targets: ["torch"], help: "Global fallback init for per-layer attention output scales." }),
      field({ env: "ATTN_SCALE_INIT_BY_LAYER", label: "Attn Scale By Layer", type: "text", value: "", targets: ["torch"], help: "Optional comma-separated per-layer override for attention scales." }),
      field({ env: "MLP_SCALE_INIT", label: "MLP Scale Init", type: "number", value: 1.0, targets: ["torch"], help: "Global fallback init for per-layer MLP output scales." }),
      field({ env: "MLP_SCALE_INIT_BY_LAYER", label: "MLP Scale By Layer", type: "text", value: "", targets: ["torch"], help: "Optional comma-separated per-layer override for MLP scales." }),
      field({ env: "RESID_MIX_INIT", label: "Resid Mix Init", type: "text", value: "1:0", targets: ["torch"], help: "Global fallback residual mix pair formatted as current:x0, for example 1:0." }),
      field({ env: "RESID_MIX_INIT_BY_LAYER", label: "Resid Mix By Layer", type: "text", value: "", targets: ["torch"], help: "Optional semicolon-separated per-layer residual mix pairs, for example 1:0;0.9:0.1;..." }),
      field({ env: "Q_GAIN_INIT_BY_LAYER", label: "Q Gain By Layer", type: "text", value: "", targets: ["torch"], help: "Optional comma-separated per-layer override for q_gain init." }),
      field({ env: "SKIP_WEIGHT_INIT", label: "Skip Weight Init", type: "number", value: 1.0, targets: ["torch"], help: "Global fallback init for encoder/decoder skip weights." }),
      field({ env: "SKIP_WEIGHT_INIT_BY_INDEX", label: "Skip Weight By Index", type: "text", value: "", targets: ["torch"], help: "Optional comma-separated per-skip override using the model's skip index order." }),
    ],
  },
  {
    title: "Optimizer",
    description: "Learning rates and momentum terms split by parameter family, including Muon-specific warmup controls.",
    fields: [
      field({ env: "EMBED_LR", label: "Untied Embed LR", type: "number", value: 0.6, targets: ["torch"], help: "Embedding LR when embeddings are not tied." }),
      field({ env: "HEAD_LR", label: "Head LR", type: "number", value: 0.008, targets: ["torch"], help: "Separate LR for an untied lm head." }),
      field({ env: "TIED_EMBED_LR", label: "Tied Embed LR", type: "number", value: 0.05, targets: ["torch", "mlx"], help: "LR for the shared token embedding / output table." }),
      field({ env: "MATRIX_LR", label: "Matrix LR", type: "number", value: 0.04, targets: ["torch", "mlx"], help: "Muon LR for 2D weight matrices." }),
      field({ env: "SCALAR_LR", label: "Scalar LR", type: "number", value: 0.04, targets: ["torch", "mlx"], help: "Adam LR for vectors, scalars, and control tensors." }),
      field({ env: "BETA1", label: "Beta1", type: "number", value: 0.9, targets: ["torch", "mlx"], help: "Adam first-moment decay." }),
      field({ env: "BETA2", label: "Beta2", type: "number", value: 0.95, targets: ["torch", "mlx"], help: "Adam second-moment decay." }),
      field({ env: "ADAM_EPS", label: "Adam Eps", type: "number", value: 1e-8, targets: ["torch", "mlx"], help: "Numerical stabilizer for Adam updates." }),
      field({ env: "MUON_MOMENTUM", label: "Muon Momentum", type: "number", value: 0.95, targets: ["torch", "mlx"], help: "Steady-state Muon momentum." }),
      field({ env: "MUON_BACKEND_STEPS", label: "Muon Backend Steps", type: "number", value: 5, targets: ["torch", "mlx"], help: "Newton-Schulz backend iterations used by Muon orthogonalization." }),
      field({ env: "MUON_MOMENTUM_WARMUP_START", label: "Muon Warmup Start", type: "number", value: 0.85, targets: ["torch", "mlx"] }),
      field({ env: "MUON_MOMENTUM_WARMUP_STEPS", label: "Muon Warmup Steps", type: "number", value: 500, targets: ["torch", "mlx"], help: "Steps used to blend from warmup momentum to final Muon momentum." }),
      field({ env: "GRAD_CLIP_NORM", label: "Grad Clip Norm", type: "number", value: 0.0, targets: ["torch", "mlx"], help: "Global gradient clipping threshold; 0 disables clipping." }),
      field({ env: "TOK_LR_MUL", label: "Tok LR Mul", type: "number", value: 1.0, targets: ["torch"], help: "Runtime multiplier applied to token-embedding optimizer groups." }),
      field({ env: "HEAD_LR_MUL", label: "Head LR Mul", type: "number", value: 1.0, targets: ["torch"], help: "Runtime multiplier applied to the untied lm_head optimizer group." }),
      field({ env: "MATRIX_LR_MUL", label: "Matrix LR Mul", type: "number", value: 1.0, targets: ["torch"], help: "Runtime multiplier applied to Muon matrix optimizer groups." }),
      field({ env: "SCALAR_LR_MUL", label: "Scalar LR Mul", type: "number", value: 1.0, targets: ["torch"], help: "Runtime multiplier applied to scalar/control Adam groups." }),
      field({ env: "ATTN_Q_LR_MUL_BY_LAYER", label: "Attn Q LR By Layer", type: "text", value: "", targets: ["torch"], help: "Optional comma-separated per-layer multiplier for attention q weights." }),
      field({ env: "ATTN_K_LR_MUL_BY_LAYER", label: "Attn K LR By Layer", type: "text", value: "", targets: ["torch"], help: "Optional comma-separated per-layer multiplier for attention k weights." }),
      field({ env: "ATTN_V_LR_MUL_BY_LAYER", label: "Attn V LR By Layer", type: "text", value: "", targets: ["torch"], help: "Optional comma-separated per-layer multiplier for attention v weights." }),
      field({ env: "ATTN_PROJ_LR_MUL_BY_LAYER", label: "Attn Proj LR By Layer", type: "text", value: "", targets: ["torch"], help: "Optional comma-separated per-layer multiplier for attention output projections." }),
      field({ env: "MLP_FC_LR_MUL_BY_LAYER", label: "MLP FC LR By Layer", type: "text", value: "", targets: ["torch"], help: "Optional comma-separated per-layer multiplier for MLP input projections." }),
      field({ env: "MLP_PROJ_LR_MUL_BY_LAYER", label: "MLP Proj LR By Layer", type: "text", value: "", targets: ["torch"], help: "Optional comma-separated per-layer multiplier for MLP output projections." }),
      field({ env: "CONTROL_LR_MUL_BY_LAYER", label: "Control LR By Layer", type: "text", value: "", targets: ["torch"], help: "Optional comma-separated per-layer multiplier for block control tensors." }),
    ],
  },
  {
    title: "Quantization Policy",
    description: "Export-time precision rules and name-based exemptions that shape the final artifact quality and size.",
    fields: [
      field({ env: "EXPORT_PROFILE", label: "Export Profile", type: "text", value: "custom", targets: ["torch"], help: "safe, balanced, aggressive, or custom. Profile values act as defaults and can still be overridden by explicit envs." }),
      field({ env: "CONTROL_TENSOR_NAME_PATTERNS", label: "Control Tensor Patterns", type: "text", value: "attn_scale,attn_scales,mlp_scale,mlp_scales,resid_mix,resid_mixes,q_gain,skip_weight,skip_weights,bigram.scale", targets: ["torch", "mlx"], help: "Parameter-name patterns treated as control tensors." }),
      field({ env: "INT8_KEEP_FLOAT_FP32_NAME_PATTERNS", label: "Keep Float FP32 Patterns", type: "text", value: "attn_scale,attn_scales,mlp_scale,mlp_scales,resid_mix,resid_mixes,q_gain,skip_weight,skip_weights,bigram.scale", targets: ["torch", "mlx"], help: "Patterns that stay float instead of quantizing." }),
      field({ env: "INT8_KEEP_FLOAT_MAX_NUMEL", label: "Keep Float Max", type: "number", value: 65536, targets: ["torch"], help: "Float tensors at or below this size can bypass quantization." }),
      field({ env: "INT8_KEEP_FLOAT_STORE_DTYPE", label: "Keep Float DType", type: "text", value: "float16", targets: ["torch"], help: "Storage dtype for float passthrough tensors: float16, bfloat16, or float32." }),
      field({ env: "INT8_CLIP_PERCENTILE", label: "Global Clip Pctl", type: "number", value: 99.99984, targets: ["torch"], help: "Global fallback clip percentile for quantization." }),
      field({ env: "DEFAULT_ROLE_BITS", label: "Default Role Bits", type: "number", value: 8, targets: ["torch"], help: "Fallback bit-width for role-aware export." }),
      field({ env: "DEFAULT_EMBED_BITS", label: "Default Embed Bits", type: "number", value: 8, targets: ["torch"], help: "Fallback embedding bit-width for export." }),
      field({ env: "EMBEDDING_BITS", label: "Embedding Bits", type: "number", value: 8, targets: ["torch"], help: "Export bit-width for token embeddings." }),
      field({ env: "EMBEDDING_CLIP_PERCENTILE", label: "Embedding Clip", type: "number", value: 99.99984, targets: ["torch"], help: "Optional clip percentile override for embeddings." }),
      field({ env: "BIGRAM_BITS", label: "Bigram Bits", type: "number", value: 8, targets: ["torch"], help: "Export bit-width for the BigramHash projection weight." }),
      field({ env: "BIGRAM_CLIP_PERCENTILE", label: "Bigram Clip", type: "number", value: 99.99984, targets: ["torch"], help: "Optional clip percentile override for the Bigram projection." }),
      field({ env: "MLP_FC_BITS", label: "MLP FC Bits", type: "number", value: 8, targets: ["torch"], help: "Export bit-width for MLP input projections." }),
      field({ env: "MLP_FC_CLIP_PERCENTILE", label: "MLP FC Clip", type: "number", value: 99.99984, targets: ["torch"], help: "Optional clip percentile override for MLP FC weights." }),
      field({ env: "MLP_PROJ_BITS", label: "MLP Proj Bits", type: "number", value: 8, targets: ["torch"], help: "Export bit-width for MLP output projections." }),
      field({ env: "MLP_PROJ_CLIP_PERCENTILE", label: "MLP Proj Clip", type: "number", value: 99.99984, targets: ["torch"], help: "Optional clip percentile override for MLP projection weights." }),
      field({ env: "ATTN_Q_BITS", label: "Attn Q Bits", type: "number", value: 8, targets: ["torch"], help: "Export bit-width for attention q projections." }),
      field({ env: "ATTN_Q_CLIP_PERCENTILE", label: "Attn Q Clip", type: "number", value: 99.99984, targets: ["torch"], help: "Optional clip percentile override for attention q weights." }),
      field({ env: "ATTN_K_BITS", label: "Attn K Bits", type: "number", value: 8, targets: ["torch"], help: "Export bit-width for attention k projections." }),
      field({ env: "ATTN_K_CLIP_PERCENTILE", label: "Attn K Clip", type: "number", value: 99.99984, targets: ["torch"], help: "Optional clip percentile override for attention k weights." }),
      field({ env: "ATTN_V_BITS", label: "Attn V Bits", type: "number", value: 8, targets: ["torch"], help: "Export bit-width for attention v projections." }),
      field({ env: "ATTN_V_CLIP_PERCENTILE", label: "Attn V Clip", type: "number", value: 99.99984, targets: ["torch"], help: "Optional clip percentile override for attention v weights." }),
      field({ env: "ATTN_PROJ_BITS", label: "Attn Proj Bits", type: "number", value: 8, targets: ["torch"], help: "Export bit-width for attention output projections." }),
      field({ env: "ATTN_PROJ_CLIP_PERCENTILE", label: "Attn Proj Clip", type: "number", value: 99.99984, targets: ["torch"], help: "Optional clip percentile override for attention output projections." }),
      field({ env: "OTHER_BITS", label: "Other Bits", type: "number", value: 8, targets: ["torch"], help: "Fallback export bit-width for uncategorized weights." }),
      field({ env: "OTHER_CLIP_PERCENTILE", label: "Other Clip", type: "number", value: 99.99984, targets: ["torch"], help: "Optional clip percentile override for uncategorized weights." }),
      field({ env: "MLP_FC_BITS_BY_LAYER", label: "MLP FC Bits By Layer", type: "text", value: "", targets: ["torch"], help: "Comma-separated per-layer override." }),
      field({ env: "MLP_PROJ_BITS_BY_LAYER", label: "MLP Proj Bits By Layer", type: "text", value: "", targets: ["torch"], help: "Comma-separated per-layer override. Supports integer bits or float." }),
      field({ env: "ATTN_Q_BITS_BY_LAYER", label: "Attn Q Bits By Layer", type: "text", value: "", targets: ["torch"], help: "Comma-separated per-layer override. Supports integer bits or float." }),
      field({ env: "ATTN_K_BITS_BY_LAYER", label: "Attn K Bits By Layer", type: "text", value: "", targets: ["torch"], help: "Comma-separated per-layer override. Supports integer bits or float." }),
      field({ env: "ATTN_V_BITS_BY_LAYER", label: "Attn V Bits By Layer", type: "text", value: "", targets: ["torch"], help: "Comma-separated per-layer override. Supports integer bits or float." }),
      field({ env: "ATTN_PROJ_BITS_BY_LAYER", label: "Attn Proj Bits By Layer", type: "text", value: "", targets: ["torch"], help: "Comma-separated per-layer override. Supports integer bits or float." }),
    ],
  },
  {
    title: "Distributed Runtime",
    description: "Torch distributed process metadata. Usually injected by the launcher rather than edited by hand.",
    fields: [
      field({ env: "RANK", label: "Rank", type: "number", value: 0, targets: ["torch"], help: "Usually injected by torchrun rather than set manually." }),
      field({ env: "WORLD_SIZE", label: "World Size", type: "number", value: 1, targets: ["torch"], help: "Usually injected by torchrun rather than set manually." }),
      field({ env: "LOCAL_RANK", label: "Local Rank", type: "number", value: 0, targets: ["torch"], help: "Usually injected by torchrun rather than set manually." }),
    ],
  },
];
